# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python version to 2.7
python: 2.7

# Run the unit test
script:
  - pip install coverage
  - coverage run tests.py

# Push the results back to codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
